{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: {{ include "monad-indexer.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "monad-indexer.fullname" . }}-backend
  labels:
    {{- include "monad-indexer.backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.backend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.backend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "monad-indexer.backend.selectorLabels" . | nindent 6 }}
{{- end }}
