---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monad-indexer-backend-secret
  namespace: monad-indexer-dev
spec:
  encryptedData:
    secret-key-base: AgBad8RAMVjnuJKHrxo9A8c9O7kePHzGHmZ4IziVCsmRoyF+jYcJRaN6BEvQcf+XEYzpmGBUXp2u/KJM+KXXagmG62VNZV72/W+6WKqvwqhL+0mBbMVaoqTR8y6hi/va27aCjIEkhRvlw1/F8dUFmdapGzEJyUoHPyvCuiHOSaz05q/Pu4ohoseTzH1iW3ukqxz/967c0Relnk0oM3l/2P6LUcQq/880PRbTDGSKyIkOwvJAIsMbiwW7W+FZKWTQmwgmfIbd96R9NH8OvnahcFS2vuNY9tQj6/7HZNmO1lmsIK92fq/uRXesgJolHCoGZiIGLXAML92M7w6W1PohRXxQk1lFm3gIFVVFsAzDcNbHPgN9wNCy+/g6uWi9ej+Utq1cv8RCwyZGKofEZSupyus3JxSM2phOx3B7XH8fXXWC3z1VyLrLcQ29MiYOsrn5j7QdwrVzBbSgyxlVl2i3ZxdEYAggNiJiL4dB/WaWMzDTYcXiwIrFB7sDmMfh4fCJG0EySupWjqESuRzw7lfNmrj0+ggEtkR+3fiL6NaqozgOQ0v5eu5UHhgrBs7swBDIVz+jAPZByPa9diOxUApovBWDUkmy75C47biH579qewjnrW2sNPdK4deRbhgj9Thb3DjYQks0ZaMVkpOygYWh5F/fUWokoW+ddolcMlOu/fUNAUoSR2Qp6z+LcUTDQZgf7p7rgv7ai8DqYmD2VJe/80jo8n7yfcwMWz5ajV1LUrxoPxCaZ0BnZcXJAmGOKNjWmUJcvfnkRDXVDIjJGHRVIdJ9b/Mvk9zEsuttGGlAzmx+eZi+lJoKqspV
  template:
    metadata:
      labels:
        app: monad-indexer
        component: backend
      name: monad-indexer-backend-secret
      namespace: monad-indexer-dev
    type: Opaque
