---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monad-indexer-backend-secret
  namespace: monad-indexer-dev
spec:
  encryptedData:
    secret-key-base: AgCDrFw7PajvA1o8YdZA+WqY639cMPri3x8+5XQm5H3/9MBh5PiP15CQJbM8GegiXr4DSY4nEld3UZt2Kg4JD9aBGQMIAxrVfonVvdXaAgfaYD10EG0JPsMI8tWLGM250GdzjFilCV6zepxEje2+mu3H0XiSr7KDt8GZm4wcgdRGeA2UnxGseFrd37NtSURnVcr4FmN71cQuuBRupFGd1rF9NKOD1AUjpfougx8OIoJ2irn9HDbQ/F3jqo3cNs98ey/l305wJB5FpK9WafEiB/4c2AhGiQ5QIPnC6F7JTtu3hMflN9rDZgXVGl/Wt62fy6nXtgIpN5+eLo5RsCQ9e15kt4uFvJyNFl16QPEPpZne5u6kncrJJjw7dZMhVn3ZMfpB2HlXK/4of3Vsoshyl0Dz2EL9zhU+RT6ddRR0QHjf2NnNJzuDlkucMSXveu/ayi8IneQR63LG1jyuNa/06J7t71V0mgTgW8f8izv+MsEeD5bZLF5zhf/CF8LjyfOkr6rR3YC4YdpjegDIF4dpGLXr7xJKJKLzSDn/TAe93+46qzv/cWV1HPWCFx2Gi4n0yRHAt19nYE4wonn0Jm88Rw/uQfTVHP1PcCq6eb3EGsL+YcAWmUcFkpuB6M7VhI8xAXUWvyqBKCHEUhnogbhJjb+oCAT3JJlRqY+54K2uDQSQ+YCTxYTqrV+o+RWyS+5ZWVpd7EqGPpAiGIKdlJjqzxWNscJFCIFyOmJ0B3dYbPClpBY0YRL4kHStY4AkdBJ0ge6rokSMsEUYAeVgwNogpxJowG+KMhH7ZS2crRXFHSOd/sCUiWDxenn9
  template:
    metadata:
      labels:
        app: monad-indexer
        component: backend
      name: monad-indexer-backend-secret
      namespace: monad-indexer-dev
    type: Opaque
