{{- if and .Values.backend.enabled (not .Values.backend.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monad-indexer.fullname" . }}-backend-secret
  labels:
    {{- include "monad-indexer.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "monad-indexer.postgresql.connectionString" . | quote }}
{{- end }}
