---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monad-indexer-stats-postgresql-app
  namespace: monad-indexer-dev
spec:
  encryptedData:
    password: AgBrmlBWCj9wqocRFZfaaUgDMgBaGCJfjWum/ACKQGobFi8MMU2N9/nJ6PoqLUhJcZek67IZqyYCpwkK/k1tI8jA+GW5dsP9qvXqmnUYB5xSOPuMfZLar+FQ3EfNQ5rrTp8h506XRin3+FmvZlIWTZVcgDFJkk9RbPJLn9+k20BdLczTca6VlIb6QqYWBMDTDZ9ICgSOgbKOTLbNsk4g3N2fgOcIho1Rd2JLE3muEklQOmpHp1CJ57mHgGguwJU3jqkfoJIWEjfsNxXchYbZzaSUR0Vxk7UHg+EgkYbb7f3xnbCzzlpvIGLLoojqpZgBKpmzca4g4k+c1ATnyeP1FsEuZ2vKZW70sjX11DuB/hjX/fNo2wbV0dtr4Dt9/RVx6PScnRTcKLVaO3S6SzFVHVzWFNKI8E0E5p2LTmVIY2ldzjD/sD3DU3ShVp6O2o8vjJ65oQIH0kAMzbi7lwKFxDtT1x5OFHNUIUmCjP74g4aFFVYtAVvTV/aiTlblTcZWFPhQxT/IBkuk60GCr8OKGPtQn7iwcUGeFu7VpeyykOdFTyHvQ9IVSvxz58Lc9Tt896rAdgfeTQuK6HyFkMtN1dgmjyMp0R83V/vHRToETZ4O0sUNRn2NKmL+OEAhNbeUHoUyCb8m/ceK4MI/YzVptQQmQEtsDUN7pf+w7muzEAY+yHtfsoXq6QFCr/L3qZlJRGTRZ3t+v7Qa7OFH9P1Ys0Benkv7DlwVIAdx+ITeDYYxSjM90xxa1MZj9EKBkg==
    username: AgBHaZJdkIgdoE1KyTLm/vB4yYx7EuViX2VIMHfQQ02DusTAFUlmbPgX+V/F3+Ro89jDyAxoUDlaFJ2VQs0Dt0o3AKNZMBa78IkSpAABMIydGh7Nx38evoK5A1fwvJF8u4BZ16prLBFEhohs1SR/BzSrfAgGMSS3971HGwCSDOSSgV6HQz3BUIEcDPtoUZJrwlwYGGqSh7F70hEgEyX5UBxd4wy3iiyDA36yd0R+2a/AI7dn4ASACMluNr9+udZg8qjuY15DF3uk+fVm28kIcwNnzfQ01BFnlZ/Pxa2ESdIs6bLeXa6Mld4V/gvL8o8FNrW7ah6okYk5sLTv2U0kZX/o+i8yAUdjd+S5Up0BZzScBXeLLCGqTUaLRiboirrP1DICLwGVpMHekp3Xh0FTaDIBHh3oog0bAfhWjqEejtVvvVa8THNRZWqz8JhVAvpSu9WvTS1lGKAOPDHPEc0bl6yA/FaTgYbEXQtN1vB4xaFAhVlYE4He+7oafR1hz4j599qa80UA9X9+aantIPo3bdE0bkYLJj8ZpK1DZvIAh9Mq4nWjFjBWXcV6PR7B8Pvtoutt+MfJcuRdE259KobLnrPoh2xKUByeplHjWlqw0H8O1XDViz8/hjc1tNIIyUR50onme+OdhH4uIFkjIkvuELtWfxDBelvCAgJI6kxPC0xsku2VSeSrU6a3BXapqX+Z9pyMzSa8QA==
  template:
    metadata:
      labels:
        app: monad-indexer
        cnpg.io/reload: "true"
        component: stats-postgresql
      name: monad-indexer-stats-postgresql-app
      namespace: monad-indexer-dev
    type: kubernetes.io/basic-auth
