{{- if and .Values.microservices.stats.enabled .Values.statsPostgresql.enabled (not .Values.statsPostgresql.auth.existingSecret) }}
{{- $password := .Values.statsPostgresql.auth.password | default (randAlphaNum 32) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monad-indexer.fullname" . }}-stats-postgresql-app
  labels:
    {{- include "monad-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/component: stats-database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.statsPostgresql.auth.username }}
  password: {{ $password | quote }}
  uri: {{ printf "postgresql://%s:%s@%s-stats-postgresql-rw:5432/%s" .Values.statsPostgresql.auth.username $password (include "monad-indexer.fullname" .) .Values.statsPostgresql.auth.database | quote }}
{{- end }}
