---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monad-indexer-postgresql-app
  namespace: monad-indexer-dev
spec:
  encryptedData:
    password: AgA71xZBNOJPchHSWFqWIFs/w4gU/HOMseg4C1S0BZVyyiKuAl1Ee2fwaa7QpZVXVdfEAHnfzhW+PD2TXl7CpE8VrxSHG85gQ+ol7tn/i3aZRpr2CQVb/fTqfCZcJR8PwynFH6bUMwFHw7KWkLGFmGI2MjxgDK8ph9hHOR+S7nRH36inr8WgfR8DELnKDnnO8DwrnhG3d/bM+x65LiCA04Qpxmwm9UFf93osjNNatLwSvFwAHsabJuaa3kqGgj2O6vO2Pb2gvKd27llWTcHq4OdewQCaPpDRyfjSG+vRu055iiRn9mvjrVNFeMDevrKT/30Y6juJrtfL7wW7vWUP+31GfJD5VeQzwBK80rya/scexxfZyvHv6L6GlzHcjxw0ynFOqZmib+4LvLFfo5IE60ostmo59QLjtqVLxxn4be5xD7kzNCswb2AVnV6DQW5Uxxxdr4y3443sPORKsyBcPiqwTlJJjxpm1dRMZFZUYtieY+qUAxqCEQln3U+4Zz4/VqcV5lt8aoC0K/EPN6QRpLukEGnwRH/xcVLxEEJzWR6kkpX/HcnjzXskfUkTKXRTf0Mq39poW5GAHF6XlU7copsClaICRsgS01jfRQppDtgVJUAy5v5/tROMicYswv49fFJWNn6qmeHTwHVgj+nJoEGxqTAu/IZqVzAA9juPaZMb2ESmyxeRJ+mmhkrDC/UrYvidHcwUaI16B7B/QF0iFZpgrxvl7ATi4Choswk+GNQviDnA0I3wDv26PmwUBQ==
    username: AgB+pqgBblSFrsEIc+7uNZGfksT/OzrOK7HEWQMhUd1pLrY/nwqh/GYmsZ9bxtx6UUuOk25cedHFjVt6P3lqlFhaQ7gPJ7E9bBbOfZmHPiD5uWKSV8Pth+y05P+S+wA/L8jCRbQrdkWtz7+KnqyDbWYr4EsnIT+T9mdAMLErA/1mbAv53lTK9+rLWBya0P4S1uYSNNZJIcNXB6AN4aRJmATNdopr8crngGoOQuWW2/dRiX38L5+XNv4NaIsU2z6m7NLQDm+OA3c8dr9E/ZxM2GYLQ7H/mrrIoyE51WphUGEEPIQGVD7JQUqTQu4Zcy2WhQytgw1Pa0w4pAHgzhAw9+88mEglnkhoUOSfWkA5NHpt2AH/LP9x8tEgyp0NKRi1jidiiXYKgn02Egzp+/vnKdM8wYbNe5bpqvVR56VVcg4ZOxkmYFP5KQ6weABOx5MH86ZN0uuYSR9Y9f0VuykfsOE960oIRCOpocsOZl17ajwVv04o5Va18dxhTApFZL8LjKCneCTgiURoaN4x9JVe6XI7X9QmbMqGFuiAUARU5irzYqD3HkR0cZ+xVD1ChqIIRWhv+eDHa6BULZ2m3Did6YYA9JKvhm6NzrOOtChDaZh0xPcA87P8EfP9Xh/31r/q5Sv5H6K62jDWdWbMuBqmBwnuZnWYyCLwaWcqxuxNmzxOGCHB4XZsc2jgXrR2wY4JabbJfgsZVOGLeUw1
  template:
    metadata:
      labels:
        app: monad-indexer
        cnpg.io/reload: "true"
        component: postgresql
      name: monad-indexer-postgresql-app
      namespace: monad-indexer-dev
    type: kubernetes.io/basic-auth
