version: '3.9'

services:
  sig-provider:
    image: ghcr.io/blockscout/sig-provider:latest
    pull_policy: always
    container_name: sig-provider
    restart: always
    env_file:
      -  ../envs/common-sig-provider.env
    ports:
      - 8151:8050
