# GRPCRoute for ArgoCD
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: argocd-grpc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - name: monad-indexer-gateway
      namespace: monad-indexer-dev
      sectionName: https-argocd
  hostnames:
    - cd.hoodscan.io
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
