{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "monad-indexer.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels: {{- include "monad-indexer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "monad-indexer.fullname" . }}-aws-secrets
    kind: SecretStore
  target:
    name: {{ .Values.backend.existingSecret }}
    creationPolicy: Owner
    {{- if .Values.postgresql.readOnlyPooler.enabled }}
    template:
      data:
        secret-key-base: {{ `"{{ .SECRET_KEY_BASE }}"` }}
        DATABASE_READ_ONLY_API_URL: {{ printf `"postgresql://blockscout:{{ .POSTGRES_PASSWORD }}@%s-pooler-ro:5432/blockscout?sslmode=disable"` (include "monad-indexer.fullname" .) }}
    {{- end }}
  data:
    - secretKey: secret-key-base
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: SECRET_KEY_BASE
    {{- if .Values.postgresql.readOnlyPooler.enabled }}
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: POSTGRES_PASSWORD
    {{- end }}
    {{- if .Values.backend.nftMediaHandler.enabled }}
    - secretKey: NFT_MEDIA_HANDLER_AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: R2_ACCESS_KEY_ID
    - secretKey: NFT_MEDIA_HANDLER_AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: R2_SECRET_ACCESS_KEY
    {{- end }}
{{- end }}
