{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "monad-indexer.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels: {{- include "monad-indexer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "monad-indexer.fullname" . }}-aws-secrets
    kind: SecretStore
  target:
    name: {{ .Values.backend.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: secret-key-base
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: SECRET_KEY_BASE
{{- end }}
