{{- if and .Values.externalSecrets.enabled .Values.postgresql.backup.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "monad-indexer.fullname" . }}-postgresql-backup-creds
  namespace: {{ .Release.Namespace }}
  labels: {{- include "monad-indexer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "monad-indexer.fullname" . }}-aws-secrets
    kind: SecretStore
  target:
    name: {{ .Values.postgresql.backup.secretName | default "postgres-backup-creds" }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ACCESS_KEY_ID: {{ printf `"{{ .POSTGRES_S3_ACCESS_KEY_ID_%s }}"` (.Values.environment | upper) }}
        SECRET_ACCESS_KEY: {{ printf `"{{ .POSTGRES_S3_SECRET_ACCESS_KEY_%s }}"` (.Values.environment | upper) }}
  data:
    - secretKey: POSTGRES_S3_ACCESS_KEY_ID_{{ .Values.environment | upper }}
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: POSTGRES_S3_ACCESS_KEY_ID_{{ .Values.environment | upper }}
    - secretKey: POSTGRES_S3_SECRET_ACCESS_KEY_{{ .Values.environment | upper }}
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: POSTGRES_S3_SECRET_ACCESS_KEY_{{ .Values.environment | upper }}
{{- end }}
