{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "monad-indexer.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels: {{- include "monad-indexer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "monad-indexer.fullname" . }}-aws-secrets
    kind: SecretStore
  target:
    name: {{ .Values.postgresql.auth.existingSecret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "blockscout"
        password: {{ `"{{ .POSTGRES_PASSWORD }}"` }}
        uri: {{- if and .Values.postgresql.pooler.enabled .Values.postgresql.pooler.useForBackend }}
          {{ printf `"postgresql://blockscout:{{ .POSTGRES_PASSWORD }}@%s-pooler:5432/blockscout?sslmode=disable"` (include "monad-indexer.fullname" .) }}
        {{- else }}
          {{ printf `"postgresql://blockscout:{{ .POSTGRES_PASSWORD }}@%s-postgresql-rw:5432/blockscout?sslmode=disable"` (include "monad-indexer.fullname" .) }}
        {{- end }}
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretName }}
        property: POSTGRES_PASSWORD
{{- end }}
