{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "monad-indexer.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels: {{- include "monad-indexer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "monad-indexer.fullname" . }}-aws-secrets
    kind: SecretStore
  target:
    name: {{ .Values.postgresql.auth.existingSecret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.aws.secretsPrefix }}/{{ .Values.externalSecrets.environment }}/postgresql
{{- end }}
