{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "monad-indexer.fullname" . }}-aws-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "monad-indexer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
      auth:
        secretRef:
          accessKeyID:
            name: {{ .Values.externalSecrets.aws.credentialsSecret }}
            key: access-key-id
          secretAccessKey:
            name: {{ .Values.externalSecrets.aws.credentialsSecret }}
            key: secret-access-key
{{- end }}
